name: Deploy to AWS

on:
  push:
    branches:
      - master  # or main, depending on your repo branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run simple test
        run: echo "Deployment starting..."
